In [2]:
import numpy as np

def luckydraw(N, total):
    lucky=np.zeros(N)
    balance=total
    for i in xrange(N):
        if i == N-1:
            lucky[i]=balance
        while lucky[i] == 0:
            lucky[i]=np.around(np.random.uniform(0.01,balance/(N-i)*2),decimals=2)
        print "红包: "+str(lucky[i])
        balance = balance-lucky[i]
        print "剩余: "+str(balance)        
    return lucky

In [3]:
luckydraw(10, 20)

红包: 2.46
剩余: 17.54
红包: 3.05
剩余: 14.49
红包: 2.03
剩余: 12.46
红包: 2.07
剩余: 10.39
红包: 1.31
剩余: 9.08
红包: 2.03
剩余: 7.05
红包: 3.42
剩余: 3.63
红包: 1.82
剩余: 1.81
红包: 1.65
剩余: 0.16
红包: 0.16
剩余: 0.0


array([ 2.46,  3.05,  2.03,  2.07,  1.31,  2.03,  3.42,  1.82,  1.65,  0.16])

### 另一种算法

In [99]:
def luckydraw2(N, total):
    div = np.random.uniform(0.01, total, N)
    m = total*div/(div.sum())
    lucky=np.around(m,2)
    #print lucky
    #print lucky.sum()
    if lucky.sum()<total: # rounding issue
        diff=total-lucky.sum()
        #print diff
        lucky[N-1] += diff
    elif lucky.sum()>total:
        diff=lucky.sum()-total
        #print diff
        lucky[N-1] -= diff
    #print lucky
    print lucky.sum()
    return lucky

In [118]:
luckydraw2(10,5)

5.0


array([ 0.97,  0.79,  0.62,  0.48,  0.41,  0.38,  0.05,  0.54,  0.04,  0.72])

In [123]:
luckydraw2(5,20)

20.0


array([ 7.48,  0.14,  8.2 ,  0.28,  3.9 ])

In [124]:
luckydraw2(10,100)

100.0


array([  8.88,  13.32,   7.4 ,  19.98,   5.29,  13.52,   7.37,   9.38,
         8.03,   6.83])